# Generated by Django 3.2.9 on 2021-11-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_en_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergies',
            table='allergies',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='nutritions',
            table='nutritions',
        ),
        migrations.AlterModelTable(
            name='product_allergies',
            table='product_allergies',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
